### PR TITLE
Unit test improvements for trivially relocatable

### PR DESCRIPTION
**Pull request by mordante**

### CODE REVIEW

**Comment by Quuxplusone** [comment]
At least on my machine, the following tests in `test/AST/` *all* fail. You're modifying only one of them?

```
    Clang :: AST/ast-dump-color.cpp
    Clang :: AST/ast-dump-decl-context-json.cpp
    Clang :: AST/ast-dump-decl.cpp
    Clang :: AST/ast-dump-invalid.cpp
    Clang :: AST/ast-dump-record-definition-data-json.cpp
    Clang :: AST/ast-dump-records-json.cpp
    Clang :: AST/ast-dump-records.cpp
    Clang :: AST/ast-dump-special-member-functions.cpp
    Clang :: AST/ast-dump-template-decls-json.cpp
```

Regardless, I'm wary of making any changes to any of these existing tests; I feel like the fix ought to be somewhere in my code. Unless all these tests are fundamentally over-fitted and ought to be relaxed somehow upstream (which would be a PR for upstream, not for my branch).

**Comment by mordante** [comment]
At my system using #1 and #2 all clang unit tests are fine.

**Comment by mordante** [comment]
Seems the force push is not easily resolved for this branch. I'll need to redo these changes.

**Comment by mordante** [comment]
Replaced by #3.

**Pull request closed without merging**
